In [3]:
import numpy as np
import pickle
import matplotlib.pyplot as plt

In [2]:
with open(r"D:\Programming\Python\Pygame\game2\models\QLearningAgentBest.pkl","rb") as f:
  q_s_a=pickle.load(f)

In [28]:
for dir in range(4):
  # plt.imshow(np.argmax(q_s_a[3,3,:,:,dir,:],axis=-1))
  print(np.argmax(q_s_a[3,3,:,:,dir,:],axis=-1))

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [ ]:
plt.figure(figsize=(10,10))
plt.plot(np.resize(q_s_a,(np.prod(q_s_a.shape[:-1],axis=0),5)),cmap=plt.colormaps()[0])
plt.show()

In [12]:
np.prod(q_s_a.shape[:-1],axis=0)

9604